[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
color-eyre = "0.6.3"
itertools = "0.12.1"
regex = "1.10.4"
bincode = { git = "https://github.com/bincode-org/bincode.git" }
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = { version = "1.0.116" }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["compression-full"] }
parser = { path = "../parser" }
derive_deref = "1.1.1"
